package com.hamsik2046.password.bean;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table account_list.
 */
public class Account implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = -4033862110914655591L;
	
	private Long id;
    /** Not-null value. */
    private String username;
    /** Not-null value. */
    private String password;
    /** Not-null value. */
    private String category;
    private String remark;
    /** Not-null value. */
    private String img_path;

    public Account() {
    }

    public Account(Long id) {
        this.id = id;
    }

    public Account(Long id, String username, String password, String category, String remark, String img_path) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.category = category;
        this.remark = remark;
        this.img_path = img_path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    /** Not-null value. */
    public String getImg_path() {
        return img_path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImg_path(String img_path) {
        this.img_path = img_path;
    }

}
