package com.hamsik2046.password.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table category_list.
 */
public class Category {

    private Long id;
    /** Not-null value. */
    private String category;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String category) {
        this.id = id;
        this.category = category;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCategory() {
        return category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(String category) {
        this.category = category;
    }

}
